spring:
  application:
    name: products
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094}
      group-id: product-scraped-event-group
      properties:
        spring:
          json:
            trusted:
              packages: com.santiago.learning.projects.webscrapping
webscrapping:
  kafka:
    topic: ${WEB_SCRAPPER_KAFKA_TOPIC:product-scraped-event-topic}
