spring:
  application:
    name: webscrapping
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      # retries: 10
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5

webscrapping:
  scheduler: ${SCHEDULER_WEB_SCRAPPER:0 0 0 */2 * *}
  webPage: ${WEB_SCRAPPER_WEB_PAGE:https://www.alkosto.com}
  kafka:
    topic: ${WEB_SCRAPPER_KAFKA_TOPIC:product-scraped-event-topic}
